name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like 'v1.0.0'
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false
      matrix:
        include:
        os: [ubuntu-latest]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install cibuildwheel pytest numpy setuptools twine

      - name: Install pybind11
        run: |
          pip install pybind11[global]

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.0
        with:
          output-dir: dist
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"

      # - name: Install package from source
      #   run: |
      #     pip install .

      # - name: Run tests
      #   run: |
      #     cd tests
      #     python3 -m pytest test.py
      #     cd ..

      # - name: Upload built wheels as artifacts (Optional)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: built-wheels
      #     path: dist/

      - name: Upload wheels to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Verify the built wheels before uploading
          twine check dist/*.whl

          # Upload the wheels to PyPI
          twine upload dist/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}